Python places within places
datacommonsorg/docsite pull request #110
Opened 2020-12-07 04:32 UTC by KilimAnnejaro

Updating this endpoint with the new examples.

2020-12-08 22:14 UTC, beets requested changes
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/110)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/python/place_in.md, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3OoM07xMsgx8QOMQH:-MO3OoM07xMsgx8QOMQI:b-a1hvzw) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L14)):*
> ```Markdown
> 
> **Signature**: `datacommons.get_places_in(dcids, place_type)`
> **Authentication**: Optional
> ```

Remove this line (also don't forget to leave an empty line between items)
___
*[api/python/place_in.md, line 34 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PILoBF_950e7GpCk:-MO3PILoBF_950e7GpCl:by3szhk) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L34)):*
> ```Markdown
> The method's return value will always be a `dict` in the following form:
> 
> ```json
> ```

python (here and below)
___
*[api/python/place_in.md, line 43 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PPnH9yPPyY3E4_9t:-MO3PPnH9yPPyY3E4_9u:bx411j8) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L43)):*
> ```
> Retrieve a list of the counties in Delaware.
> ```
Perhaps: Retrieve a list of all counties in Delaware
___
*[api/python/place_in.md, line 48 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PbH58JsZn1Awv0-U:-MO3PbH58JsZn1Awv0-V:b4yauvo) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L48)):*
> ```
> dc
> ```
datacommons, to match the signature above
___
*[api/python/place_in.md, line 79 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PfKz4QHh6d8DhT5G:-MO3PfKz4QHh6d8DhT5H:b-fxksc6) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L79)):*
> ```Markdown
> #### Response
> 
> ##### Raw
> ```

Drop "raw" responses for python (we always return parsed results)
___
*[api/python/place_in.md, line 101 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PlsS-LnIDCv-hIaW:-MO3PlsS-LnIDCv-hIaX:b1frv15) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L101)):*
> ```Markdown
> ## Error Returns
> 
> If there is no value associated with the property, an empty list is returned:
> ```

Maybe: no value associated with the _requested_ property


<!-- Sent from Reviewable.io -->

2020-12-11 05:20 UTC, KilimAnnejaro reviewed
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/110)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/place_in.md, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3OoM07xMsgx8QOMQH:-MOFDLdZBubHfCin9FlX:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L14)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Remove this line (also don't forget to leave an empty line between items)
</blockquote></details>

Done.
___
*[api/python/place_in.md, line 34 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PILoBF_950e7GpCk:-MOFDZN04-aO8FZTag66:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L34)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

python (here and below)
</blockquote></details>

Done.
___
*[api/python/place_in.md, line 43 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PPnH9yPPyY3E4_9t:-MOFDbNs6bkBzJ9j-Ujv:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L43)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

> ```
> Retrieve a list of the counties in Delaware.
> ```
Perhaps: Retrieve a list of all counties in Delaware
</blockquote></details>

Done.
___
*[api/python/place_in.md, line 48 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PbH58JsZn1Awv0-U:-MOFDnTc1S4AcGdYkeno:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L48)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

> ```
> dc
> ```
datacommons, to match the signature above
</blockquote></details>

Done.
___
*[api/python/place_in.md, line 79 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PfKz4QHh6d8DhT5G:-MOFDugg-GwjghWGAtxE:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L79)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Drop "raw" responses for python (we always return parsed results)
</blockquote></details>

Done.
___
*[api/python/place_in.md, line 101 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/110#-MO3PlsS-LnIDCv-hIaW:-MOFEP-U9vfz5rJrgy00:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/7d979d5dc6bc7081bc50f28a75dbb27cac3b01e6/api/python/place_in.md#L101)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Maybe: no value associated with the _requested_ property
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-11 17:59 UTC, beets approved these changes

2020-12-11 17:59 UTC, beets commented
Thanks for the updates! Merging..

2020-12-11 17:59 UTC, merged