Python stat value polished first draft
datacommonsorg/docsite pull request #117
Opened 2020-12-12 18:40 UTC by KilimAnnejaro

Polished first draft for the stat-value method for Python.

2021-01-20 00:16 UTC, beets requested changes
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/117)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/python/stat_value.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS6uQi04fqLd-tohKB:-MRS6uQi04fqLd-tohKC:b-d4sbdm) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L9)):*
> ```Markdown
> ---
> 
> # Get Statistics Value for a Place
> ```

Maybe update Get -> Retrieve ?
___
*[api/python/stat_value.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS71Qn2p0UCOZByR1r:-MRS71Qn2p0UCOZByR1s:b-r1l9o) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L20)):*
> ```Markdown
> ## General information about this endpoint
> 
> **Signature**: `datacommons.get_stat_value(place, stat_var, date=None, measurement_method=None,observation_period=None, unit=None, scaling_factor=None)`
> ```

Use ```python here instead
___
*[api/python/stat_value.md, line 24 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS75I2AcQf61pLjZGV:-MRS75I2AcQf61pLjZGW:b-qyuxlb) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L24)):*
> ```Markdown
> **Required arguments**:
> 
> * `place`: The DCID of the [`Place`](https://datacommons.org/browser/Place) to query for.
> ```

Should we link to glossary for DCID here and below?
___
*[api/python/stat_value.md, line 46 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS7JWU3DAWwnlFUTpd:-MRS7JWU3DAWwnlFUTpe:b-x6vc0s) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L46)):*
> ```Markdown
> In addition to these required properties, this method also allows for other, optional arguments. Here are helpful arguments in regular use by Data Commons developers:
> 
>   - [`date`](/glossary.html): Specified in ISO 8601 format.
> ```

These look quite repetitive compared to above "optional arguments" list now, especially since we've moved most of the details into the glossary. What do you think?


<!-- Sent from Reviewable.io -->

2021-01-27 05:14 UTC, KilimAnnejaro reviewed
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/117)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/stat_value.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS6uQi04fqLd-tohKB:-MS1Cpq16aAEG2uthtzw:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Maybe update Get -> Retrieve ?
</blockquote></details>

Done.
___
*[api/python/stat_value.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS71Qn2p0UCOZByR1r:-MS1D--R46Mir4_BgK5g:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L20)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Use ```python here instead
</blockquote></details>

Done.
___
*[api/python/stat_value.md, line 24 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS75I2AcQf61pLjZGV:-MS1E2au8VjyHFZjO88B:b52dudb) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L24)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Should we link to glossary for DCID here and below?
</blockquote></details>

I added a link for this line. I'm a little uncertain about linking to the glossary again for the DCID word mention below--I don't know that the Google style guide forbids relinking, but on Wikipedia the style guide (https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Linking) recommends not overlinking. So for example, in an article about K2, I would only link to Mount Everest's page once per paragraph (at the point of first appearance).
If you think it would be better to link below too, I can do that for sure!
___
*[api/python/stat_value.md, line 46 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS7JWU3DAWwnlFUTpd:-MS1FMCi0BSSNFAVT5Gy:btk14w7) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L46)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

These look quite repetitive compared to above "optional arguments" list now, especially since we've moved most of the details into the glossary. What do you think?
</blockquote></details>

I decided to try to follow the example from https://docs.datacommons.org/api/rest/stat_value.html. There's still some repetition, but not quite so much--let me know what you think!


<!-- Sent from Reviewable.io -->

2021-02-02 05:07 UTC, beets reviewed
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/117)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/stat_value.md, line 24 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS75I2AcQf61pLjZGV:-MSW7jbu8AjCrdaJYL2d:bk7jio1) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L24)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

I added a link for this line. I'm a little uncertain about linking to the glossary again for the DCID word mention below--I don't know that the Google style guide forbids relinking, but on Wikipedia the style guide (https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Linking) recommends not overlinking. So for example, in an article about K2, I would only link to Mount Everest's page once per paragraph (at the point of first appearance).
If you think it would be better to link below too, I can do that for sure!
</blockquote></details>

just linking once sounds good
___
*[api/python/stat_value.md, line 46 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/117#-MRS7JWU3DAWwnlFUTpd:-MSW7bBa8wJr7RjrIiur:bbo24j7) ([raw file](https://github.com/datacommonsorg/docsite/blob/efb8b5d3db203f5b48f15f179ccc7bf499236898/api/python/stat_value.md#L46)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

I decided to try to follow the example from https://docs.datacommons.org/api/rest/stat_value.html. There's still some repetition, but not quite so much--let me know what you think!
</blockquote></details>

looks good!


<!-- Sent from Reviewable.io -->

2021-02-02 05:07 UTC, beets approved these changes

2021-02-02 05:07 UTC, merged