Pandas time series dataframe
datacommonsorg/docsite pull request #119
Opened 2020-12-13 03:59 UTC by KilimAnnejaro

Polished first draft on updating this doc.

2021-02-02 05:28 UTC, beets requested changes
sorry for the delay - this looks good, only a couple of minor updates

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/119#-:-MSWCcFe3oBtHGxjX_hh:b-daepwc)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/pandas/time_series_dataframe.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/119#-MSWCUzi3WTyTgzjCsp5:-MSWCUzi3WTyTgzjCsp6:bi08in0) ([raw file](https://github.com/datacommonsorg/docsite/blob/a743ecd9ec77d777787f5d6c5c4c7e85bd1e605c/api/pandas/time_series_dataframe.md#L9)):*
> ```Markdown
> ---
> 
> # Get Time Series DataFrame
> ```

Get -> Retrieve
___
*[api/pandas/time_series_dataframe.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/119#-MSWCW9sBkN55vfNK4lL:-MSWCW9sBkN55vfNK4lM:b-uaucu) ([raw file](https://github.com/datacommonsorg/docsite/blob/a743ecd9ec77d777787f5d6c5c4c7e85bd1e605c/api/pandas/time_series_dataframe.md#L20)):*
> ```Markdown
> ## General information about this method
> 
> **Signature**: `datacommons_pandas.build_time_series_dataframe(places, stat_var)`
> ```

use ```python here


<!-- Sent from Reviewable.io -->

2021-02-06 04:30 UTC, KilimAnnejaro reviewed
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/119)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

___
*[api/pandas/time_series_dataframe.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/119#-MSWCUzi3WTyTgzjCsp5:-MSpaSmK-30vbumL0xK1:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/a743ecd9ec77d777787f5d6c5c4c7e85bd1e605c/api/pandas/time_series_dataframe.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Get -> Retrieve
</blockquote></details>

Done.
___
*[api/pandas/time_series_dataframe.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/119#-MSWCW9sBkN55vfNK4lL:-MSpagzYD8NxWFxvoB1o:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/a743ecd9ec77d777787f5d6c5c4c7e85bd1e605c/api/pandas/time_series_dataframe.md#L20)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

use ```python here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 17:55 UTC, beets reviewed
looks good - thanks! merging..

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/119#-:-MT6voNmAGTLW37mVbmx:bwr9p0o)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @tjann)



<!-- Sent from Reviewable.io -->

2021-02-09 17:56 UTC, beets approved these changes

2021-02-09 17:56 UTC, merged