Python triple docs first pass
datacommonsorg/docsite pull request #136
Opened 2021-01-09 02:50 UTC by KilimAnnejaro

Updating the docs for the Python triple method.

2021-01-20 00:22 UTC, beets requested changes
Thanks! Could we also carry over some of the triple key explanations from the REST docs?

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/136#-:-MRS9d4t7S2CWNoYXO3C:bh2iwhm)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @KilimAnnejaro)

___
*[api/python/triple.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/136#-MRS8uDQEGFKSTRqyloL:-MRS8uDQEGFKSTRqyloM:b-wsynio) ([raw file](https://github.com/datacommonsorg/docsite/blob/0d4667e570f609dd7b367d8c10a2e9d7276b73ff/api/python/triple.md#L9)):*
> ```Markdown
> ---
> 
> # Show Triples Associated with Node(s)
> ```

Maybe "Retrieve" instead of "Show"?
___
*[api/python/triple.md, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/136#-MRS8xQC2WRVPrWmK08l:-MRS8xQC2WRVPrWmK08m:btm3u9e) ([raw file](https://github.com/datacommonsorg/docsite/blob/0d4667e570f609dd7b367d8c10a2e9d7276b73ff/api/python/triple.md#L16)):*
> ```Markdown
> ## General information about this endpoint
> 
> **Signature**: `datacommons.get_triples(dcids, limit=datacommons.utils._MAX_LIMIT)`
> ```

Use ```python here
___
*[api/python/triple.md, line 43 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/136#-MRS9pRCBC2HiuJw2Uoy:-MRS9pRCBC2HiuJw2Uoz:bstt5xc) ([raw file](https://github.com/datacommonsorg/docsite/blob/0d4667e570f609dd7b367d8c10a2e9d7276b73ff/api/python/triple.md#L43)):*
> ```Markdown
>     ...
> }
> ```
> ```

please expand this section to match the REST docs
___
*[api/python/triple.md, line 58 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/136#-MRS9IP5DeH8Lp2QHuil:-MRS9IP5DeH8Lp2QHuim:b-mpvijf) ([raw file](https://github.com/datacommonsorg/docsite/blob/0d4667e570f609dd7b367d8c10a2e9d7276b73ff/api/python/triple.md#L58)):*
> ```Markdown
> 
> ```python
> {'SquareMeter1238495': [('SquareMeter1238495', 'typeOf', 'Quantity'), ('SquareMeter1238495', 'provenance', 'dc/sm3m2w3'), ('geoId/12086008906', 'landArea', 'SquareMeter1238495')]}
> ```

I think this is a typo (it should be lower-case squareMeter1238495, and it's a quantity, not a place). 

Could we update this example with a more traditional place ID? For shorter ones, you can use a zip code (eg dcid: zip/94043)


<!-- Sent from Reviewable.io -->

2021-01-29 04:58 UTC, KilimAnnejaro reviewed
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/136)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @beets)

___
*[api/python/triple.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/136#-MRS8uDQEGFKSTRqyloL:-MSBQSK63PWX9c3wlAcy:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/dd9f65a510bdec8c88945661cfedc5e538747459/api/python/triple.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Maybe "Retrieve" instead of "Show"?
</blockquote></details>

Done.
___
*[api/python/triple.md, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/136#-MRS8xQC2WRVPrWmK08l:-MSBQWu85sk2Rmv2FOg9:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/dd9f65a510bdec8c88945661cfedc5e538747459/api/python/triple.md#L16)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Use ```python here
</blockquote></details>

Done.
___
*[api/python/triple.md, line 43 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/136#-MRS9pRCBC2HiuJw2Uoy:-MSBQXwGExTfW2WZnoNI:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/dd9f65a510bdec8c88945661cfedc5e538747459/api/python/triple.md#L43)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

please expand this section to match the REST docs
</blockquote></details>

Done.
___
*[api/python/triple.md, line 58 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/136#-MRS9IP5DeH8Lp2QHuil:-MSBVL1NC1lU7_h9-y8G:b88agmq) ([raw file](https://github.com/datacommonsorg/docsite/blob/dd9f65a510bdec8c88945661cfedc5e538747459/api/python/triple.md#L58)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

I think this is a typo (it should be lower-case squareMeter1238495, and it's a quantity, not a place). 

Could we update this example with a more traditional place ID? For shorter ones, you can use a zip code (eg dcid: zip/94043)
</blockquote></details>

Done. I also changed some formatting here and below.


<!-- Sent from Reviewable.io -->

2021-02-02 05:09 UTC, beets commented
looks good, thanks!

2021-02-02 05:09 UTC, beets approved these changes

2021-02-02 05:09 UTC, merged