Intro rewrite
datacommonsorg/docsite pull request #77
Opened 2020-09-29 01:03 UTC by KilimAnnejaro

First pass on rewriting the intro.

2020-10-05 16:09 UTC, beets requested changes
This is nice! Sorry for the late review, I just have a few small comments.

2020-10-05 16:09 UTC, beets commented on contributing/adding_datasets.md
> +Check in the Template MCF file together with the cleaned CSV, its preprocessing script (if needed), and the README to [https://github.com/datacommonsorg/data](https://github.com/datacommonsorg/data)
Instead of "check in", should we say "send a pull request"? Not sure what the accepted term is for github.

2020-10-06 23:57 UTC, tjann approved these changes

2020-10-06 23:57 UTC, tjann commented on contributing/adding_datasets.md
> +3. Dates must be in ISO 8601 format: "YYYY-MM-DD".
Technically no, but we strongly prefer as long as the obs period is obvious

2020-10-06 23:57 UTC, tjann commented on contributing/adding_datasets.md
> +Once you've generated the MCF, write a README following the template at <https://github.com/datacommonsorg/data/tree/master/scripts/example_provenance/example_dataset>. Finally, check in the MCF file
Maybe use this link for second link: https://github.com/datacommonsorg/data/tree/master/scripts/example_provenance/example_dataset

2020-10-07 00:05 UTC, beets approved these changes

2020-10-07 00:06 UTC, beets commented
Thanks Anne - I'll merge this in and work on the suggested fixes from this PR as a follow up

2020-10-07 00:06 UTC, merged